### ISSUE TITLE
AddPrimitiveWord (and maybe others) should convert to upper

### ISSUE THREAD

**Issue by Thraka** [enif77/EFrt#1]
I noticed while implementing an interpreter that it seems the input keyword text (sorry if I use the wrong terms, I'm super new to forth) is translating to string upper. When I added my own word that was lower, it wouldn't match the input. I had to use an upper case string when adding the word. If this is by design, it should just convert the word string to upper when defining it.

This code:
```csharp
            interpreter.AddPrimitiveWord("colorf", .........
```
didn't work when typing "colorf" into the input stream. When I defined the word as:
```csharp
            interpreter.AddPrimitiveWord("COLORF",  ........
```
then the word "colorf" worked in the input stream.

**Comment by enif77** [comment]
Hello, its actually a good idea. Thanks for it! 

Explanation: The words list is internally case sensitive. So if I wanted a case insensitive words searching (during compilation etc.), I decided to store all words in upercase so I can search for them more easilly. All words in libs are prepared for that (their names are uppercase), so the AddPrimitiveWord() method works perfectly. The word : uses ToUpperInvariant() to add a new user defined word, so the case insensitive words searching works again. But the AddPrimitiveWord() method does no case conversion, which causes problem, you described. I'll add it there.

**Comment by enif77** [comment]
Feature added, all commited and updated nuget packages released.
